// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnolgoyhqbqilkgaakgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdub2xnb3locWJxaWxrZ2Fha2dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDgwOTcsImV4cCI6MjA2NDAyNDA5N30.4Ozwe7-qaRdXGuFq3x2U7oyB6LmpHRAmsPhVlYldzXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);